language: python
python: 3.5

env:
  - TOXENV=py35
  - TOXENV=py34
  - TOXENV=py33
  - TOXENV=py27
  - TOXENV=pypy

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox

# command to run tests, e.g. python setup.py test
script: tox -e ${TOXENV}

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: $PYPI_USER
  password:
    secure: $PYPI_PASSWORD
  on:
    tags: true
    repo: 5monkeys/python-ncs
    condition: $TOXENV == py27
